save1 = Savegame.create(name:"Save 1",size:5)

Field.create(savegame:save1,x:0,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:1,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:2,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:3,y:0,is_mine:true,used:false,marked:false)
Field.create(savegame:save1,x:4,y:0,is_mine:false,used:false,marked:false)

Field.create(savegame:save1,x:0,y:1,is_mine:false,used:true,marked:false)
Field.create(savegame:save1,x:1,y:1,is_mine:false,used:true,marked:false)
Field.create(savegame:save1,x:2,y:1,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:3,y:1,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:4,y:1,is_mine:false,used:false,marked:false)

Field.create(savegame:save1,x:0,y:2,is_mine:false,used:true,marked:false)
Field.create(savegame:save1,x:1,y:2,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:2,y:2,is_mine:true,used:false,marked:false)
Field.create(savegame:save1,x:3,y:2,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:4,y:2,is_mine:false,used:false,marked:false)

Field.create(savegame:save1,x:0,y:3,is_mine:false,used:true,marked:false)
Field.create(savegame:save1,x:1,y:3,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:2,y:3,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:3,y:3,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:4,y:3,is_mine:false,used:false,marked:false)

Field.create(savegame:save1,x:0,y:4,is_mine:false,used:true,marked:false)
Field.create(savegame:save1,x:1,y:4,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:2,y:4,is_mine:true,used:false,marked:false)
Field.create(savegame:save1,x:3,y:4,is_mine:false,used:false,marked:false)
Field.create(savegame:save1,x:4,y:4,is_mine:false,used:false,marked:false)

save2 = Savegame.create(name:"Save 2",size:5)

Field.create(savegame:save2,x:0,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:1,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:2,y:0,is_mine:true,used:false,marked:false)
Field.create(savegame:save2,x:3,y:0,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:4,y:0,is_mine:false,used:false,marked:false)

Field.create(savegame:save2,x:0,y:1,is_mine:false,used:true,marked:false)
Field.create(savegame:save2,x:1,y:1,is_mine:false,used:true,marked:false)
Field.create(savegame:save2,x:2,y:1,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:3,y:1,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:4,y:1,is_mine:false,used:false,marked:false)

Field.create(savegame:save2,x:0,y:2,is_mine:false,used:true,marked:false)
Field.create(savegame:save2,x:1,y:2,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:2,y:2,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:3,y:2,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:4,y:2,is_mine:false,used:false,marked:false)

Field.create(savegame:save2,x:0,y:3,is_mine:false,used:true,marked:false)
Field.create(savegame:save2,x:1,y:3,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:2,y:3,is_mine:true,used:false,marked:false)
Field.create(savegame:save2,x:3,y:3,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:4,y:3,is_mine:false,used:false,marked:false)

Field.create(savegame:save2,x:0,y:4,is_mine:false,used:true,marked:false)
Field.create(savegame:save2,x:1,y:4,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:2,y:4,is_mine:true,used:false,marked:false)
Field.create(savegame:save2,x:3,y:4,is_mine:false,used:false,marked:false)
Field.create(savegame:save2,x:4,y:4,is_mine:false,used:false,marked:false)
